---
- name: Setup dev tools
  block:

    - name: Download VS Code
      ansible.builtin.get_url:
        url: https://code.visualstudio.com/sha/download?build=stable&os=linux-rpm-x64
        dest: "/home/{{ setup_instructlab_user }}/vscode.rpm"

    - name: Install VS Code
      shell: "sudo rpm -ivh /home/{{ setup_instructlab_user }}/vscode.rpm"

    - name: Download sdkman installer
      ansible.builtin.get_url:
        url: https://get.sdkman.io
        dest: "/home/{{ setup_instructlab_user }}/sdkman-installer.sh"
        mode: 0755

    - name: Install sdkman
      shell: "bash /home/{{ setup_instructlab_user }}/sdkman-installer.sh"

    - name: Run sdkman installer
      shell: source "/home/{{ setup_instructlab_user }}/.sdkman/bin/sdkman-init.sh"

    - name: Install Java using sdkman
      shell: |
        chmod +x /home/{{ setup_instructlab_user }}/.sdkman/contrib/completion/bash/sdk
        /home/{{ setup_instructlab_user }}/.sdkman/contrib/completion/bash/sdk install java 21.0.3-tem
      become: true
      register: java_install

    - name: Check Java installation
      debug:
        msg: "Java {{ java_install.stdout }} installed successfully."
      when: java_install.rc == 0

    - name: Create directory with specific owner and group
      file:
        path: "/home/{{ setup_instructlab_user }}/instructlab/models"
        state: directory
        mode: "0755" 

    - name: Download LLM for RAD (Parasol Model)
      ansible.builtin.get_url:
        url: https://huggingface.co/rh-rad-ai-roadshow/parasol-merlanite-trained-GGUF/resolve/main/parasol-model-0715-sdg400.gguf?download=true
        dest: "/home/{{ setup_instructlab_user }}/instructlab/models/parasol-model.gguf"
        mode: 0644
      register: llm_download_result

    - name: Check LLM download status 
      debug:
        msg: "LLM download {{ llm_download_result.msg }}"
      when: llm_download_result is defined

    - name: Download a custom policy document
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/rh-rad-ai-roadshow/parasol-insurance/main/app/src/main/resources/claims/marty-mcfly-auto.pdf
        dest: "/home/{{ setup_instructlab_user }}/Documents/marty-mcfly-auto.pdf"
        mode: 0644

    - name: Create a new directory
      file:
        path: "/home/{{ setup_instructlab_user }}/parasol-insurance"
        state: directory
        mode: 0755

    - name: Clone parasol-insurance repository
      git:
        repo: https://github.com/rh-rad-ai-roadshow/parasol-insurance.git
        dest: "/home/{{ setup_instructlab_user }}/parasol-insurance"

    - name: Change owner of the parasol-insurance directory
      file:
        path: "/home/{{ setup_instructlab_user }}/parasol-insurance"
        recurse: true
        mode: 0755

    # - name: Check parasol app location
    #   shell: |
    #     ls -al /home/{{ setup_instructlab_user }}/parasol-insurance
    #     ls -al /home/{{ setup_instructlab_user }}/parasol-insurance/app
    #   register: r_result

    # - name: Show output
    #   debug:
    #      msg: "{{ r_result.stdout }}" 

    - name: Build the parasol app
      shell: |
        cd /home/{{ setup_instructlab_user }}/parasol-insurance/app/
        /home/{{ setup_instructlab_user }}/parasol-insurance/app/mvnw clean package -DskipTests"

    - name: Run the parasol app in background
      shell: "nohup java -jar -Dquarkus.langchain4j.openai.parasol-chat.base-url=http://localhost:8000/v1 /home/{{ setup_instructlab_user }}/parasol-insurance/app/target/quarkus-app/quarkus-run.jar > ~/quarkus.out 2>&1 &"

    - name: Create settings directory for VS Code
      file:
        path: "/home/{{ setup_instructlab_user }}/.config/Code/User"
        state: directory
        mode: 0755

    - name: Create settings file
      ansible.builtin.copy:
        src: settings.json
        dest: "/home/{{ setup_instructlab_user }}/.config/Code/User/settings.json"
        mode: u=rw,g=rw,o=
        creates: "/home/{{ setup_instructlab_user }}/.config/Code/User/settings.json"

  become: true
  become_user: "{{ setup_instructlab_user }}"
